#configfile config.yaml
#workdir: /homes/kanotebomer/Documents/Thema11/Thema11-Dataprocessing/Assignment_3
workdir: /home/skippybal/PycharmProjects/Thema11-Dataprocessing/Assignment_3/
url: https://bioinf.nl/~fennaf/snakemake/WC03/data/
genome: data/A
ext : .fa
samples:
    A : /data/A.bam
    B : /data/B.bam
    C : /data/C.bam
    D : /data/D.bam
    E : /data/E.bam
    F : /data/F.bam
    G : /data/G.bam
    H : /data/H.bam
    I : /data/I.bam
